languageCode = "zh-TW"
baseurl = "https://masonchu.github.io/"
title = "KY Chu"
theme = "strange-case"
tags = ["microservice", "golang"]
features = ["responsive", "thumbnail", "grid", "syntax highlight", "structured data", "ogp", "twitter cards"]

[params]
    colorScheme = "scheme-lightbrown"
    DateFormat = "2006/01/02"
    description = "Build Awesome Things"
    sidebarDescription = "Build Awesome Things"
    sidebarFreeText = ""


[[menu.main]]
    name = "Hugo"
    post = "<span class='glyphicon glyphicon-fire'></span>"
    url = "http://gohugo.io"

[[menu.main]]
    name = "Bootstrap"
    post = "<span class='glyphicon glyphicon-ok'></span>"
    url = "http://getbootstrap.com"