languageCode = "zh-TW"
baseurl = "https://masonchu.github.io/"
title = "Mason Chu"
theme = "hugo-theme-learn"
googleAnalytics = "UA-28614097-1"
tags = ["microservice", "golang"]
features = ["responsive", "thumbnail", "grid", "syntax highlight", "structured data", "ogp", "twitter cards"]

# [params]
#     colorScheme = "scheme-lightbrown"
#     DateFormat = "2006/01/02"
#     description = "Build Awesome Things"
#     sidebarDescription = "Build Awesome Things"
#     sidebarFreeText = ""
#     themeVariant = "blue"
[params]
    # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
    # Useful to give opportunity to people to create merge request for your doc.
    # See the config.toml file from this documentation site to have an example.
    editURL = ""
    # Author of the site, will be used in meta information
    author = "masonchu"
    # Description of the site, will be used in meta information
    description = "Build Awesome Things"
    # Shows a checkmark for visited pages on the menu
    showVisitedLinks = false
    # Disable search function. It will hide search bar
    disableSearch = false
    # Javascript and CSS cache are automatically busted when new version of site is generated. 
    # Set this to true to disable this behavior (some proxies don't handle well this optimization)
    disableAssetsBusting = false
    # Set this to true to disable copy-to-clipboard button for inline code.
    disableInlineCopyToClipBoard = false
    # A title for shortcuts in menu is set by default. Set this to true to disable it. 
    disableShortcutsTitle = false
    # When using mulitlingual website, disable the switch language button.
    disableLanguageSwitchingButton = false
    # Order sections in menu by "weight" or "title". Default to "weight"
    ordersectionsby = "weight"
    # Change default color scheme with a variant one. Can be "red", "blue", "green".
    themeVariant = "blue"
[outputs]
    home = [ "HTML", "RSS", "JSON"]
[[menu.shortcuts]] 
    name = "<i class='fa fa-github'></i> Github"
    identifier = "ds"
    url = "https://github.com/masonchu"
    weight = 10
[[menu.shortcuts]] 
    name = "<i class='fa fa-linkedin'></i> Linkedin"
    identifier = "in"
    url = "https://www.linkedin.com/in/masonchu/"
    weight = 11
[[menu.shortcuts]] 
    name = "<i class='fa fa-stack-overflow'></i> Stack Overflow"
    identifier = "so"
    url = "https://stackoverflow.com/users/1053261/mason"
    weight = 11

# [[menu.shortcuts]] 
#     name = "linkedin"
#     post = "<span class='fa fa-linkedin'></span>"
#     url = "https://www.linkedin.com/in/masonchu/"

# [[menu.shortcuts]] 
#     name = "github"
#     post = "<span class='fa fa-github'></span>"
#     url = "https://github.com/masonchu"