languageCode = "zh-TW"
baseurl = "https://masonchu.github.io/"
title = "Mason Chu"
theme = "strange-case"
tags = ["microservice", "golang"]
features = ["responsive", "thumbnail", "grid", "syntax highlight", "structured data", "ogp", "twitter cards"]

[params]
    colorScheme = "scheme-lightbrown"
    DateFormat = "2006/01/02"
    description = "Build Awesome Things"
    sidebarDescription = "Build Awesome Things"
    sidebarFreeText = ""


[[menu.main]]
    name = "linkedin"
    post = "<span class='fa fa-linkedin'></span>"
    url = "https://www.linkedin.com/in/masonchu/"

[[menu.main]]
    name = "github"
    post = "<span class='fa fa-github'></span>"
    url = "https://github.com/masonchu"